### ISSUE TITLE
Please help me by addressing the below mentioned issue

### ISSUE THREAD

**Issue by Guru426** [gianlucamangiapelo/wdio-azure-devops-service#11]
hello @gianlucamangiapelo please help me by addressing the below mentioned issue

i am trying to publish the test results to Azure Devops testcase using your custom service: AzureDevopsService and added that to wdio.config.js file and set all the project, test plan related attributes like below.. also added a test case ID to a test but its not able to publish the test results.. i am quite sure that the azure token and values are perfect as they are working fine via postman.. need to know where I am doing wrong...

 services: [
    [
      'appium',
      {
        args: {
          address: 'localhost',
          port: 4724
        },
        logPath: './'
      }
    ],
    [
      AzureDevopsService,
      {
          pat: 'tokenvalue',
          organizationUrl: 'https://dev.azure.com/orgid',
          projectId: 'projectid',
          planId: 6496,
          suiteId: 6497,
          // caseIdRegex: '@?[cC](https://github.com/gianlucamangiapelo/wdio-azure-devops-service/blob/master///d+)',
          caseIdRegex: '(\\d+)',
          runName: 'Demo',
          caseId: 6547
      },
  ]

and in the test script i am using like below:

describe('6547 sample',() => {
    it('6547 sample test', async () => {
        await driver.pause(10000);
    })
})

I am blocked due to this issue, please HELP

_Originally posted by @Guru426 in https://github.com/gianlucamangiapelo/wdio-azure-devops-service/issues/6#issuecomment-1520819051_

**Comment by Guru426** [comment]
I found that the service is not getting initialised at all. this is how I am importing const AzureDevopsService = require ('@gmangiapelo/wdio-azure-devops-service'); in wdio.config.js and also added dependancies in package.json using npm install

**Comment by gianlucamangiapelo** [comment]
Ciao @Guru426 How did you resolve the issue?
Thanks
