### ISSUE TITLE
Error import EMCA

### ISSUE THREAD

**Issue by GGiuseppe91** [gianlucamangiapelo/wdio-azure-devops-service#16]
Hello, I need help, when trying to import the module with import AzureDevopsService from '@gmangiapelo/wdio-azure-devops-service'; i receive this errror 
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
ERROR @wdio/config:ConfigParser: Failed loading configuration file: .../wdio.conf.js: Cannot use import statement outside a module
\node_modules\@gmangiapelo\wdio-azure-devops-service\dist\esm\index.js:1
import AzureDevopsService from './azure-devops-service';
^^^^^^
I have set in my package.json the "type": "module", but I still receive this error can someone help?

**Comment by godfather029** [comment]
I am still facing this issue. @gianlucamangiapelo can you help

![Image](https://github.com/user-attachments/assets/1eced715-1d64-42f1-9995-3fd6d18fa7e7)

![Image](https://github.com/user-attachments/assets/80a3deee-43b5-486e-961c-4ea451c31091)

![Image](https://github.com/user-attachments/assets/d75e85bb-da83-44b6-8014-f9f5f304a45b)

**Comment by gianlucamangiapelo** [comment]
@godfather029 I will have a look during the week.
